# GitHub Sponsors (org/bruker – endre til dine faktiske)
github: [lexinav, julianberge]

# Open Collective (slug)
open_collective: lexinav

# Patreon (creator name)
patreon: lexinav

# Ko-fi (brukernavn)
ko_fi: lexinav

# Buy Me a Coffee (brukernavn)
buy_me_a_coffee: lexinav

# Tidelift (ecosystem/package)
tidelift: npm/lexinav

# Community Bridge (prosjektnavn)
community_bridge: lexinav

# Liberapay (brukernavn)
liberapay: lexinav

# IssueHunt (repo/org)
issuehunt: lexinav

# Otechie (profil)
otechie: julian-berge

# LFX Crowdfunding (prosjektnavn)
lfx_crowdfunding: lexinav

# Egendefinerte lenker (din landingsside, Base44, osv.)
custom:
  - "https://lexinav.no/sponsor"
  - "https://opencollective.com/lexinav"
  - "https://github.com/sponsors/lexinav"
